### ISSUE TITLE
Lab 2 notes

### ISSUE THREAD

**Issue by AntonC9018** [grxxnzzz/ASD_USM#2]
https://github.com/grxxnzzz/ASD_USM/blob/d8bb12c63efd60b37be261c6f0c053ca3370b0ed/ASD_Lab2/main.cpp#L21-L22
Это ты использовал индексирование, и перешел на 2 элемент, а не на 3. По pointer arithmetic есть в доке пример.

https://github.com/grxxnzzz/ASD_USM/blob/d8bb12c63efd60b37be261c6f0c053ca3370b0ed/ASD_Lab2/main.cpp#L9-L10
Здесь просять определить, т.е. в один этап. Заревьювь терминологию.

Форматни файл. https://www.quora.com/What-does-it-mean-to-format-your-code

Вторую часть не сделал.

**Comment by AntonC9018** [comment]
> Насчёт **pointer arithmetic** мне тогда надо сделать так: 
> `iPointer = iPointer +2;` при учёте, что до этого будет написано это: `iPointer = &arr[0];`?

Ага

**Comment by AntonC9018** [comment]
Определить значит объявить + инициализировать в 1 действие. То есть по итогу в новой переменной будет какое-то значение.

Чисто технически, объявить локальную переменную без инициализации невозможно в c++, потому что по умолчанию она инициализирована рандомным мусором, который остался в той памяти. В C# например, локальную переменную до инициализации тупо невозможно использовать (не дает считать значения), в C++ такой системы нету

**Comment by AntonC9018** [comment]
То что ты назвал определить — это называется объявить.

**Comment by grxxnzzz** [comment]
Понял, спасибо

**Comment by AntonC9018** [comment]
https://github.com/grxxnzzz/ASD_USM/blob/eb78a27fc041a368569071d4538adceacd901b09/ASD_Lab2/example.cpp#L49
Не адрес всей структуры, а адрес 3 элемента из массива в той структуре. Но ты понял по идее, просто дописывать лень было.

https://github.com/grxxnzzz/ASD_USM/blob/eb78a27fc041a368569071d4538adceacd901b09/ASD_Lab2/example.cpp#L52
Адрес значения -- такого не бывает. Адрес может быть памяти = адрес переменной. Значение это что, что хранится в памяти. Значения не привязаты к той или иной памяти.
