### ISSUE TITLE
Lab 3 Notes

### ISSUE THREAD

**Issue by AntonC9018** [grxxnzzz/ASD_USM#3]
https://github.com/grxxnzzz/ASD_USM/blob/19c338f62031f515b1c9bae3e581e70679705f48/ASD_Lab3/explanation.md?plain=1#L111
Знаю. Но без оптимизации по факту случится что? Почему указатели равны? Объясни то что иллюстрируется.
Я знаю что это UB, и в самом примере это упомянуто. Но суть примера не в этом.

https://github.com/grxxnzzz/ASD_USM/blob/19c338f62031f515b1c9bae3e581e70679705f48/ASD_Lab3/explanation.md?plain=1#L122
for us? ☭

👍

**Comment by grxxnzzz** [comment]
> for us? ☭
👍

имелось в виду, что это то, на что обращаем внимание, когда говорим про разницу между этими двумя файлами

**Comment by AntonC9018** [comment]
Лайк на работу, не на СССР)

**Comment by grxxnzzz** [comment]
выглядело, как ирония 🤨
